### ISSUE TITLE
CUMR 1 - Registrar Proveedor

### ISSUE THREAD

**Issue by ergo-program** [fatimaTalavera/ON_project#15]
Se debe seguir el modelo de planillas especificados en el documento DRIVE "Modelado de Requisitos"

**Comment by mirtara** [comment]
@ergo-program es importante definir ya todos los campos, entonces cuando estas en los siguientes procesos de diseño, como diagrama de clases, prototipo de ui, ya tenes esos campos y no hace falta re-pensarlo. @fatimaTalavera
