### ISSUE TITLE
CUMR 5 - Cuenta Corriente Proveedores

### ISSUE THREAD

**Issue by ergo-program** [fatimaTalavera/ON_project#18]
Se debe seguir el modelo de planillas especificados en el documento DRIVE "Modelado de Requisitos"

**Comment by fatimaTalavera** [comment]
Unificamos Cta Cte para las facturas de servicios y compras, ya que lo único que difiere es que uno es cliente y el otro proveedor. 
Quedaría en CUMR 5 - Cuenta Corriente

**Comment by mirtara** [comment]
@taniamonges hice algunas modificaicones, están en el documento en drive, en Tania Monges.docx.
