### ISSUE TITLE
DDA 1 - Registrar Proveedor

### ISSUE THREAD

**Issue by taniamonges** [fatimaTalavera/ON_project#29]
Realizar diagrama de actividades, ver ejemplo del libro Ingenieria de Software - Pressman pag: 138

**Comment by mirtara** [comment]
@ergo-program tu primera actividad dice Registrar proveedor, deberia decir cargar datos del proveedor, al completar todos los pasos el proveedor queda registrado. Fijate DDA-15 Registro de usuario

**Comment by ergo-program** [comment]
@mirtara Cambios Realizados.
