### ISSUE TITLE
DDA 4 - Facturas Compras

### ISSUE THREAD

**Issue by taniamonges** [fatimaTalavera/ON_project#32]
Realizar diagrama de actividades, ver ejemplo del libro Ingenieria de Software - Pressman pag: 138

**Comment by mirtara** [comment]
@fatimaTalavera en tu diagrama dice condition, debe decir condicion y en vez de si/no debe ser contado/credito.

**Comment by fatimaTalavera** [comment]
@mirtara cambios realizados
