### ISSUE TITLE
DDA 6 - Registrar Cliente 

### ISSUE THREAD

**Issue by taniamonges** [fatimaTalavera/ON_project#34]
Realizar diagrama de actividades, ver ejemplo del libro Ingenieria de Software - Pressman pag: 138

**Comment by mirtara** [comment]
@ergo-program tu primera actividad dice Registrar clientes, deberia decir cargar datos del cliente, al completar todos los pasos el cliente queda registrado. Fijate DDA-15 Registro de usuario

**Comment by ergo-program** [comment]
@mirtara Cambios realizados.
