### ISSUE TITLE
DDA 11 - Facturar Servicios

### ISSUE THREAD

**Issue by taniamonges** [fatimaTalavera/ON_project#39]
Realizar diagrama de actividades, ver ejemplo del libro Ingenieria de Software - Pressman pag: 138

**Comment by mirtara** [comment]
@alexjw no es correcto que la primera actividad sea Crear una factura, cuando eso es el resultado de seguir todos los pasos.
El primer paso seria buscar al cliente. Fijate DDA-14 (donde primero se busca al jornalero)
