### ISSUE TITLE
Diseño Interface - Proveedores

### ISSUE THREAD

**Issue by taniamonges** [fatimaTalavera/ON_project#52]

**Comment by mirtara** [comment]
@taniamonges Falta dato fundamental de proveedor que es RUC

**Comment by mirtara** [comment]
@taniamonges parece que correo es obligatorio, porque tiene *, considero que este campo deberia ser opcional, ya que seguro habrá proveedores sin correo.

**Comment by taniamonges** [comment]
@mirtara  listo
