### ISSUE TITLE
Diseño de Interface - Factura Compra

### ISSUE THREAD

**Issue by taniamonges** [fatimaTalavera/ON_project#55]

**Comment by mirtara** [comment]
@taniamonges cambiar tipo de pago, por condicion de pago (factura contado/ vs factura credito)
EN el formulario para crear la factura falta el campo Nro de factura, para saber el nro de factura que te dio tu proveedor. En tu lista veo que si aparece el campo nro.

**Comment by taniamonges** [comment]
si listo
